import Product from '../models/Product.js';

// @desc    Fetch all products with pagination, search, and filter
// @route   GET /api/products
// @access  Public
export const getProducts = async (req, res) => {
  try {
    const pageSize = Number(req.query.limit) || 12;
    const page = Number(req.query.page) || 1;

    const keyword = req.query.keyword
      ? {
          name: {
            $regex: req.query.keyword,
            $options: 'i',
          },
        }
      : {};

    const category = req.query.category ? { category: req.query.category } : {};
    const subcategory = req.query.subcategory ? { subcategory: req.query.subcategory } : {};
    const brand = req.query.brand ? { brand: { $regex: req.query.brand, $options: 'i' } } : {};
    const minRating = req.query.minRating ? { ratings: { $gte: Number(req.query.minRating) } } : {};
    const priceFilter = {};
    if (req.query.minPrice) priceFilter.$gte = Number(req.query.minPrice);
    if (req.query.maxPrice) priceFilter.$lte = Number(req.query.maxPrice);
    const price = Object.keys(priceFilter).length ? { price: priceFilter } : {};

    // Only show published products unless admin
    const isPublished = req.user && req.user.role === 'admin' && req.query.all === 'true' 
      ? {} 
      : { isPublished: true, stock: { $gt: 0 } };

    const query = { ...keyword, ...category, ...subcategory, ...brand, ...minRating, ...price, ...isPublished };

    const count = await Product.countDocuments(query);
    const products = await Product.find(query)
      .limit(pageSize)
      .skip(pageSize * (page - 1))
      .sort({ createdAt: -1 });

    res.json({ products, page, pages: Math.ceil(count / pageSize), count });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// @desc    Fetch single product by slug or ID
// @route   GET /api/products/:slug
// @access  Public
export const getProductBySlug = async (req, res) => {
  try {
    const identifier = req.params.slug;
    const isObjectId = identifier.match(/^[0-9a-fA-F]{24}$/);
    
    const query = isObjectId 
      ? { $or: [{ _id: identifier }, { slug: identifier }] }
      : { slug: identifier };
      
    const product = await Product.findOne(query);

    if (product) {
      res.json(product);
    } else {
      res.status(404).json({ message: 'Product not found' });
    }
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// @desc    Create a product
// @route   POST /api/products
// @access  Private/Admin
export const createProduct = async (req, res) => {
  try {
    const product = new Product({
      name: req.body.name || 'Sample name',
      price: req.body.price || 0,
      description: req.body.description || 'Sample description',
      images: req.body.images || [],
      brand: req.body.brand || 'Sample brand',
      category: req.body.category || 'Sample category',
      subcategory: req.body.subcategory || undefined,
      stock: req.body.stock || 0,
      isPublished: req.body.isPublished || false,
      seoTitle: req.body.seoTitle || '',
      seoDescription: req.body.seoDescription || '',
      seoKeywords: req.body.seoKeywords || [],
      seller: req.user._id,
      // slug is auto-generated by pre-validate hook
    });

    const createdProduct = await product.save();
    res.status(201).json(createdProduct);
  } catch (error) {
    if (error.code === 11000) {
      return res.status(400).json({
        message: 'A listing with a similar title already exists. Try a more specific book title.',
      });
    }
    res.status(400).json({ message: error.message });
  }
};

// @desc    Update a product
// @route   PUT /api/products/:id
// @access  Private/Admin
export const updateProduct = async (req, res) => {
  try {
    const product = await Product.findById(req.params.id);

    if (product) {
      // Update fields dynamically
      Object.keys(req.body).forEach(key => {
        if (req.body[key] !== undefined) {
          product[key] = req.body[key];
        }
      });

      const updatedProduct = await product.save();
      res.json(updatedProduct);
    } else {
      res.status(404).json({ message: 'Product not found' });
    }
  } catch (error) {
    res.status(400).json({ message: error.message });
  }
};

// @desc    Delete a product
// @route   DELETE /api/products/:id
// @access  Private/Admin
export const deleteProduct = async (req, res) => {
  try {
    const product = await Product.findById(req.params.id);

    if (product) {
      await product.deleteOne();
      res.json({ message: 'Product removed' });
    } else {
      res.status(404).json({ message: 'Product not found' });
    }
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// @desc    Get recommendations
// @route   GET /api/products/recommendations
// @access  Public
export const getRecommendations = async (req, res) => {
  try {
    const { productId } = req.query;
    let category = '';

    if (productId) {
      const product = await Product.findById(productId);
      if (product) category = product.category;
    }

    // Simple recommendation logic: find by same category, or just featured
    const query = category ? { category, _id: { $ne: productId }, isPublished: true } : { isFeatured: true, isPublished: true };
    
    const products = await Product.find(query).limit(4);
    res.json(products);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};
